binding: support YAML format
flamego/binding pull request #16
Opened 2021-11-30 07:34 UTC by Germiniku

binding support yaml validator

2021-11-30 08:37 UTC, unknwon requested changes
Thanks for your PR!

However, please first fill out the PR description using the [pre-filled template](https://github.com/flamego/binding/blob/main/.github/pull_request_template.md).

We can only review after that's been done.

2021-11-30 08:56 UTC, Germiniku commented
> Thank you for submitting this PR!
> 
> Unfortunately, we are not able to review changes until you have time to take the little extra effort to fill out the PR description using the [pre-filled template](https://github.com/flamego/binding/blob/main/.github/pull_request_template.md).

I've changed it to this template now

2021-11-30 09:12 UTC, unknwon requested changes

2021-11-30 09:12 UTC, unknwon commented on binding.go
> +	"gopkg.in/yaml.v3"
```suggestion

	"gopkg.in/yaml.v3"

	"github.com/flamego/flamego"
	"github.com/flamego/validator"
```

ref: https://github.com/unknwon/go-code-convention/blob/main/en-US.md#import-packages

2021-11-30 09:12 UTC, unknwon commented on binding.go
> +func Yaml(model interface{}, opts ...Options) flamego.Handler {
```suggestion
// YAML returns a middleware handler that injects a new instance of the model
// with populated fields and binding.Errors for any deserialization, binding, or
// validation errors into the request context. The model instance fields are
// populated by deserializing the YAML payload from the request body.
func YAML(model interface{}, opts ...Options) flamego.Handler {
```

Please also fix other occurrences.

2021-11-30 09:12 UTC, unknwon commented on binding.go
> +				panic("binding.Yaml: " + err.Error())
```suggestion
				panic("binding.YAML: " + err.Error())
```

2021-11-30 09:12 UTC, unknwon commented on binding_test.go
> +func TestYaml(t *testing.T) {
```suggestion
func TestYAML(t *testing.T) {
```

2021-11-30 09:12 UTC, unknwon commented on binding_test.go
> +
Looks like a test similar to ["invalid JSON"](https://github.com/flamego/binding/blob/dbd21dca85f5a72c9ffe7fcfac551f5a40f93ac4/binding_test.go?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L36) is missing?

2021-11-30 09:12 UTC, unknwon commented on binding_test.go
> +			{
Also missing a similar test to "invalid JSON"?

2021-11-30 09:12 UTC, unknwon commented on go.mod
> +	gopkg.in/yaml.v3 v3.0.0-20210107192922-496545a6307b // indirect
This is a direct dependency, please do a `go mod tidy`.

2021-11-30 09:12 UTC, unknwon commented on binding_test.go
> +			Password: supersecurepassword`,
The formatting here looks weird, why is it looking like this?

2021-11-30 09:47 UTC, Germiniku commented
Sorry，I made some stupid mistakes.

2021-11-30 09:57 UTC, unknwon commented
> Sorry，I made some stupid mistakes.

No need to be sorry at all :)

2021-12-01 02:54 UTC, Germiniku commented
I have now increased YAML test coverage to 95.2%

2021-12-01 03:05 UTC, unknwon requested changes
Thanks for the followup!

Left few more comments.

2021-12-01 03:05 UTC, unknwon commented on binding.go
> +	"gopkg.in/yaml.v3"
@Germiniku This has not been addressed.

2021-12-01 03:05 UTC, unknwon commented on binding_test.go
> +
@Germiniku I think here we are still missing the test case without "custom error handler".

2021-12-01 03:05 UTC, unknwon commented on binding_test.go
> +				req.Header.Set("Content-Type", "application/x-yaml")
Is there a MDN page recommending setting this value? Seems not necessary be put here.

2021-12-01 03:37 UTC, Germiniku commented
Content-Type application/x-yaml  i have not found on MDN. this is a found on stackoverflow link [https://stackoverflow.com/questions/332129/yaml-media-type](url)

2021-12-01 03:53 UTC, unknwon approved these changes
Thank you, all looking good!

2021-12-01 03:53 UTC, unknwon commented on binding_test.go
> +	type address struct {
```suggestion
	})

	type address struct {
```

2021-12-01 03:53 UTC, unknwon commented on binding_test.go
> +				assert.Equal(t, test.statusCode, resp.Code)
```suggestion
				assert.Nil(t, err)

				f.ServeHTTP(resp, req)

				assert.Equal(t, test.statusCode, resp.Code)
```

2021-12-01 03:53 UTC, unknwon commented on binding_test.go
> +			test.assertErrors(t, gotErrs)
```suggestion
			assert.Nil(t, err)

			f.ServeHTTP(resp, req)

			test.assertErrors(t, gotErrs)
```

2021-12-01 04:05 UTC, merged

2021-12-01 04:06 UTC, unknwon commented
Congratulations 🎉 and https://github.com/flamego/binding/releases/tag/v1.1.0 has been tagged for this merge!